# https://stackoverflow.com/questions/61388905/github-action-to-maven-build-followed-by-docker-build-push
# https://zhuanlan.zhihu.com/p/90122357

name: Docker CI for dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image on dev
        run: >-
          sudo apt-get install -y maven;
          export APP_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)-snapshot-$(date +%Y%m%d);
          docker login -u geekyouth -p ${{ secrets.DOCKER_CI_TOKEN }};
          docker build . -f Dockerfile -t geekyouth/crack-dbeaver-password:${APP_VERSION};
          docker build . -f Dockerfile -t geekyouth/crack-dbeaver-password:latest-snapshot;
          docker push geekyouth/crack-dbeaver-password:${APP_VERSION};
          docker push geekyouth/crack-dbeaver-password:latest-snapshot;

---
name: Docker CI for master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: >-
          sudo apt-get install -y maven;
          export APP_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout);
          docker login -u geekyouth -p ${{ secrets.DOCKER_CI_TOKEN }};
          docker build . -f Dockerfile -t geekyouth/crack-dbeaver-password:${APP_VERSION};
          docker build . -f Dockerfile -t geekyouth/crack-dbeaver-password:latest;
          docker push geekyouth/crack-dbeaver-password:${APP_VERSION};
          docker push geekyouth/crack-dbeaver-password:latest;

---
name: Maven package for master

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      #    - name: Build with Maven
      #      run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: >-
          mvn deploy source:jar -q -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
